#!/bin/sh

set -ue

TARGET=/srv/nm.debian.org/htdocs/static

cd /srv/nm.debian.org/nm2/

for src in */static
do
	# Create dirs
	for dir in `find $src -type d -printf '%P\n' | sed -e '/^$/d'`
	do
		install -m 0755 -d $TARGET/$dir
	done

	# Copy files
	for file in `find $src -type f -printf '%P\n'`
	do
		install -m 0644 $src/$file $TARGET/$file
	done
done

rm -rf $TARGET/admin
cp -r /usr/share/pyshared/django/contrib/admin/media $TARGET/admin
